sudo: false
language: node_js
node_js:
  - "5.0"
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - develop
    - master
script:
  - npm run test:coverage
after_success:
  - npm run coveralls
deploy:
  provider: heroku
  api_key: 4fd3f4ce-2f6a-49c7-b238-21dd660db329
  app:
    develop: media-gallery
    master: media-gallery
before_deploy:
  - npm i pushstate-server -g
